<?php
$z[0]=Array("channel","\r\n                    <dd>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </dd>\r\n                    ",404,640);
$z[0][4]=array();
$z[0][4]['row']="4";
$z[0][4]['type']="son";
$z[0][4]['typeid']="1";
$z[1]=Array("channel","\r\n                    <dd>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </dd>\r\n                    ",905,1141);
$z[1][4]=array();
$z[1][4]['row']="4";
$z[1][4]['type']="son";
$z[1][4]['typeid']="3";
$z[2]=Array("channel","\r\n                    <dd>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </dd>\r\n                    ",1411,1647);
$z[2][4]=array();
$z[2][4]['row']="4";
$z[2][4]['type']="son";
$z[2][4]['typeid']="4";
$z[3]=Array("channel","\r\n                    <dd>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </dd>\r\n                    ",1917,2153);
$z[3][4]=array();
$z[3][4]['row']="4";
$z[3][4]['type']="son";
$z[3][4]['typeid']="5";
$z[4]=Array("channel","\r\n                    <dd>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </dd>\r\n                    ",2420,2656);
$z[4][4]=array();
$z[4][4]['row']="4";
$z[4][4]['type']="son";
$z[4][4]['typeid']="7";
$z[5]=Array("global","",2826,2858);
$z[5][4]=array();
$z[5][4]['name']="cfg_templets_skin";

?>